global:
  # with this false, you cannot use item names, but you can use custom blocks
  # GLOBAL ONLY
  use-match-material: true
  chest-loot:
  sponsor-loot:

chests:

itemsets:

rewards:
  # Every one of the below will be given

  # The max amount of items that can be given to a player randomly
  max-random: 5
  # The following will be randomly given to the player
  random:

kits: