name: MyHungerGames
main: com.randude14.hungergames.HungerGames
version: 0.5.2-dev
authors: [Randude14, kitskub]
softdepend: [Vault, HawkEye, LogBlock]

commands:
    hga:
        description: admin hungergames command
        usage:
    hg:
        description: user hungergames command
        usage:
        
permissions:
                        