name: MyHungerGames
main: me.kitskub.hungergames.HungerGames
version: 1.2-dev
authors: [kitskub, Randude14]
softdepend: [Vault, HawkEye, LogBlock, Multiverse-Adventure, Multiverse-Core]
description: A plugin that provides functionality similar to and more than the HungerGames. Sponsored be treepuncher.com

commands:
    hga:
        description: admin hungergames command
        usage:
    hg:
        description: user hungergames command
        usage:
        
permissions:
                        