name: MyHungerGames
main: com.randude14.hungergames.HungerGames
version: 0.9.2
authors: [kitskub, Randude14]
softdepend: [Vault, HawkEye, LogBlock, Multiverse-Adventure]
description: A plugin that provides functionality similar to and more than the HungerGames. Sponsored be treepuncher.com

commands:
    hga:
        description: admin hungergames command
        usage:
    hg:
        description: user hungergames command
        usage:
        
permissions:
                        