properties:
    join-message: '<player> has joined the game <game>.'
    rejoin-message: '<player> has rejoined the game <game>'
    leave-message: '<player> has left the game <game>.'
    kill-message: '<killer> killed <killed> in game <game>.'
    vote-message: '<player> is ready to play <game>. Type /hg vote when you are ready to play.'
    default-game: 'Test'
    default-time: 10
    min-vote: 5
    allow-join-during-game: false
    update-delay: 30
    min-players: 2
    allow-rejoin: true
    winner-keeps-items: true
chest-loot:
# Example loot. Note DURABIlITY is an enchantment
#    DIAMOND_PICKAXE:
#        stack-size: 1
#        chance: 0.01
#        DURABILITY: 3
sponsor-loot:
  