name: MyHungerGames
main: com.randude14.hungergames.HungerGames
version: 0.8
authors: [kitskub, Randude14]
softdepend: [Vault, HawkEye, LogBlock]

commands:
    hga:
        description: admin hungergames command
        usage:
    hg:
        description: user hungergames command
        usage:
        
permissions:
                        