name: HungerGames
main: com.randude14.hungergames.Plugin
version: 0.2.2
authors: [Randude14, kitskub]
softdepend: [Vault]

commands:
    hga:
        description: admin hungergames command
        usage:
    hg:
        description: user hungergames command
        usage:
        
permissions:
    hungergame.admin.*:
        description: enables all admin perms
        children:
            hungergame.add.game: false
            hungergame.add.spawnpoint: false
            hungergame.add.chest: false
            hungergame.add.itemset: false
            hungergame.remove.game: false
            hungergame.remove.spawnpoint: false
            hungergame.remove.chest: false
            hungergame.remove.itemset: false
            hungergame.set.enabled: false
            hungergame.set.spawn: false
            hungergame.game.start: false
            hungergame.admin.reload: false
            hungergame.admin.kick: false            
            hungergame.admin.help: false
    hungergame.user.*:
        description: enables all basic user perms
        children:
            hungergame.user.join: false
            hungergame.user.leave: false
            hungergame.user.rejoin: false    
            hungergame.user.list: false
            hungergame.user.stat: false
            hungergame.user.vote: false
            hungergame.user.sponsor: false            
            hungergame.user.help: false
            
    hungergame.add.game:
        default: false
        description: create a game
    hungergame.add.spawnpoint:
        default: false
        description: add a spawnpoint
    hungergame.add.chest:
        default: false
        description: add a chest
    hungergame.add.itemset:
        default: false
        description: add an itemset
    hungergame.remove.game:
        default: false
        description: remove a game
    hungergame.remove.spawnpoint:
        default: false
        description: remove a spawnpoint
    hungergame.remove.chest:
        default: false
        description: remove a chest 
    hungergame.set.enabled:
        default: false
        description: 'enable/disable a game'
    hungergame.set.spawn:
        default: false
        description: set the spawn for a game        
    hungergame.game.start:
        default: false
        description: start a game
    hungergame.admin.kick:
        default: false
        description: kick a player       
    hungergame.admin.reload:
        default: false
        description: reload plugin
    hungergame.admin.help:
        default: false
        description: get admin commands
    hungergame.user.join:
        default: false
        description: join a game
    hungergame.user.leave:
        default: false
        description: leave a game
    hungergame.user.list:
        default: false
        description: list available games
    hungergame.user.stat:
        default: false
        description: list stats of a game
    hungergame.user.vote:
        default: false
        description: vote for a game
    hungergame.user.rejoin:
        default: false
        description: rejoin a game
    hungergame.user.sponsor:
        default: false
        description: sponsor a player an item           
    hungergame.user.help:
        default: false
        description: get user commands
       
                        