name: HungerGames
main: com.randude14.hungergames.Plugin
version: 0.2.2
authors: [Randude14, kitskub]
softdepend: [Vault]

commands:
    hga:
        description: admin hungergames command
        usage:
    hg:
        description: user hungergames command
        usage:
        
permissions:
    hungergame.*:
       description: enables all permissions
       children:
           hungergame.admin.*: true
           hungergame.user.*: true
    hungergame.admin.*:
        description: enables all admin perms
        children:
            hungergame.add.game: true
            hungergame.add.spawnpoint: true
            hungergame.add.chest: true
            hungergame.add.itemset: true
            hungergame.remove.game: true
            hungergame.remove.spawnpoint: true
            hungergame.remove.chest: true
            hungergame.remove.itemset: true
            hungergame.set.enabled: true
            hungergame.set.spawn: true
            hungergame.game.start: true
            hungergame.admin.reload: true
            hungergame.admin.kick: true            
            hungergame.admin.help: true
    hungergame.user.*:
        description: enables all basic user perms
        children:
            hungergame.user.join: true
            hungergame.user.leave: true
            hungergame.user.rejoin: true    
            hungergame.user.list: true
            hungergame.user.stat: true
            hungergame.user.vote: true
            hungergame.user.sponsor: true            
            hungergame.user.help: true

    hungergame.add.game:
        default: false
        description: create a game
    hungergame.add.spawnpoint:
        default: false
        description: add a spawnpoint
    hungergame.add.chest:
        default: false
        description: add a chest
    hungergame.add.itemset:
        default: false
        description: add an itemset
    hungergame.remove.game:
        default: false
        description: remove a game
    hungergame.remove.spawnpoint:
        default: false
        description: remove a spawnpoint
    hungergame.remove.chest:
        default: false
        description: remove a chest 
    hungergame.set.enabled:
        default: false
        description: 'enable/disable a game'
    hungergame.set.spawn:
        default: false
        description: set the spawn for a game        
    hungergame.game.start:
        default: false
        description: start a game
    hungergame.admin.kick:
        default: false
        description: kick a player       
    hungergame.admin.reload:
        default: false
        description: reload plugin
    hungergame.admin.help:
        default: false
        description: get admin commands
    hungergame.user.join:
        default: false
        description: join a game
    hungergame.user.leave:
        default: false
        description: leave a game
    hungergame.user.list:
        default: false
        description: list available games
    hungergame.user.stat:
        default: false
        description: list stats of a game
    hungergame.user.vote:
        default: false
        description: vote for a game
    hungergame.user.rejoin:
        default: false
        description: rejoin a game
    hungergame.user.sponsor:
        default: false
        description: sponsor a player an item           
    hungergame.user.help:
        default: false
        description: get user commands
       
                        